# Generated by Django 2.2 on 2020-09-05 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Project's name")),
                ('date_start', models.DateTimeField(verbose_name='Start of the project')),
                ('date_end', models.DateTimeField(verbose_name='End of the project')),
                ('project_type', models.IntegerField(choices=[(1, 'Inner'), (2, 'Social'), (3, 'Commercial')], verbose_name='Type of the project')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Role Name')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UserToProjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='main.Projects', verbose_name='Project')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.UserRoles', verbose_name='Role of the user')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
