# Generated by Django 2.2 on 2020-09-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='date_end',
            field=models.DateField(verbose_name='End of the project'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='date_start',
            field=models.DateField(verbose_name='Start of the project'),
        ),
    ]
