# Generated by Django 2.2 on 2020-09-05 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200905_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoprojects',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='main.Projects', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='usertoprojects',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.UserRoles', verbose_name='Role of the user'),
        ),
        migrations.AlterField(
            model_name='usertoprojects',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
