# Generated by Django 2.2 on 2020-09-05 17:55

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200905_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='description',
            field=models.TextField(default='bla-bla-bla', verbose_name='Description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='product_owner',
            field=models.CharField(default='Medina Nurlan kyzy', max_length=100, verbose_name='Product Owner'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ProjectsDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datafile', models.FileField(upload_to=main.models.upload_location, verbose_name='File')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.Projects', verbose_name='Project')),
            ],
        ),
    ]
