# Generated by Django 2.2 on 2020-09-05 18:03

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200905_1755'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.upload_location, verbose_name='Image')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.Projects', verbose_name='Project')),
            ],
        ),
    ]
